/control/verbose 2
/control/saveHistory
/run/verbose 2

/vis/open OGL 1920x1080-0+0

/vis/enable

# re-enabled later
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -3 2 -2
/vis/viewer/set/lightsVector -1 0 0

/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/endOfEventAction accumulate

/hit_sim/set_gap_width 100 um
/hit_sim/set_particle_energy 50 MeV
/hit_sim/set_detector_variant backplate_water
/hit_sim/set_backplate_thickness 25 mm
# /hit_sim/set_detector_variant backplate_chip
#/hit_sim/set_backplate_thickness 0.35 mm

/run/initialize
/run/beamOn 1000
